version: "3.8"
services:
  nginx_master:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_master
    volumes:
      - $PWD/data/logs/nginx/master:/var/log/nginx
      - $PWD/nginx/master.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/keepalived-master.conf:/etc/keepalived/keepalived.conf
    networks:
      frontend:
        ipv4_address: 10.0.0.3
    cap_add: 
      - NET_ADMIN
    
  nginx_slave:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_slave
    volumes:
      - $PWD/data/logs/nginx/slave:/var/log/nginx
      - $PWD/nginx/slave.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    networks:
      frontend:
        ipv4_address: 10.0.0.4
    cap_add: 
        - NET_ADMIN

  proxy:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - 8080:80
    volumes:
      - $PWD/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - nginx_master
      - nginx_slave
    networks:
      frontend:
        ipv4_address: 10.0.0.2

networks:
  frontend:
    name: frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/24 # 可用地址:254;掩码:255.255.255.0;网络:10.0.0.0;第一个可用:10.0.0.1;最后可用:10.0.0.254;广播:10.0.0.255
