version: "3.8"
services:
  api_master:
    build:
      context: $PWD/api
      dockerfile: Dockerfile
    container_name: api_master
    # ports:
    #   - 8081:8081
    environment:
      TIME_ZONE: Asia/Shanghai
      GIN_MODE: release
      PORT: 8080
      NAMESPACE: api master gateway
    volumes:
      - $PWD/data/logs/api/1:/var/api/log
    networks:
      - backend
  
  api_slave:
    build:
      context: $PWD/api
      dockerfile: Dockerfile
    container_name: api_slave
    # ports:
    #   - 8082:8082
    environment:
      TIME_ZONE: Asia/Shanghai
      GIN_MODE: release
      PORT: 8080
      NAMESPACE: api slave gateway
    volumes:
      - $PWD/data/logs/api/2:/var/api/log
    networks:
      - backend

  nginx_master:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_master
    volumes:
      - $PWD/data/logs/nginx/master:/var/log/nginx
      - $PWD/nginx/master.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-master.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - api_master
      - api_slave
    networks:
      frontend:
        ipv4_address: 10.0.0.3
      backend:
    cap_add: 
      - NET_ADMIN
    
  nginx_slave:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_slave
    volumes:
      - $PWD/data/logs/nginx/slave:/var/log/nginx
      - $PWD/nginx/slave.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - api_master
      - api_slave
    networks:
      frontend:
        ipv4_address: 10.0.0.4
      backend:
    cap_add: 
        - NET_ADMIN

  proxy:
    build:
      context: $PWD/haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    ports:
      - 8080:80
    environment:
      TIME_ZONE: Asia/Shanghai
    volumes:
      - $PWD/config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - nginx_master
      - nginx_slave
    networks:
      frontend:
        ipv4_address: 10.0.0.2

networks:
  frontend:
    name: frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.1/24 # 可用地址:254;掩码:255.255.255.0;网络:10.0.0.0;第一个可用:10.0.0.1;最后可用:10.0.0.254;广播:10.0.0.255
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24
