version: "3.9"
services:
  nginx_master:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_master
    volumes:
      - $PWD/data/logs/nginx/master:/var/log/nginx
      - $PWD/nginx/master.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-master.conf:/etc/keepalived/keepalived.conf
    privileged: true
    networks:
      - web_nginx 
    ports:
      - 8081:80
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    
  nginx_slave:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_slave
    volumes:
      - $PWD/data/logs/nginx/slave:/var/log/nginx
      - $PWD/nginx/slave.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    privileged: true
    networks:
      - web_nginx
    ports:
      - 8082:80
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW

  proxy:
    build:
      context: $PWD/haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - $PWD/config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - nginx_master
      - nginx_slave
    network_mode: host
    ports:
      - 8080:80

networks:
  web_nginx:
    name: web
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24 # 可用地址:254;掩码:255.255.255.0;网络:172.20.0.0;第一个可用:172.20.0.1;最后可用:172.20.0.254;广播:172.20.0.255
          gateway: 172.20.0.1
  