version: "3"
services:
  api_master:
    build:
      context: $PWD/api
      dockerfile: Dockerfile
    container_name: api_master
    privileged: true
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
      PORT: 18081
      NAMESPACE: api master gateway
    volumes:
      - $PWD/data/logs/api/master:/var/api/log
    network_mode: host
    ports:
      - 18081:18081
  
  api_slave:
    build:
      context: $PWD/api
      dockerfile: Dockerfile
    container_name: api_slave
    privileged: true
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
      PORT: 18082
      NAMESPACE: api slave gateway
    volumes:
      - $PWD/data/logs/api/2:/var/api/log
    network_mode: host
    ports:
      - 18082:18082

  nginx_master:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_master
    privileged: true
    volumes:
      - $PWD/data/logs/nginx/master:/var/log/nginx
      - $PWD/nginx/master.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-master.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - api_master
      - api_slave
    network_mode: host
    ports:
      - 8081:80
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    
  nginx_slave:
    build:
      context: $PWD/nginx
      dockerfile: Dockerfile
    container_name: nginx_slave
    privileged: true
    volumes:
      - $PWD/data/logs/nginx/slave:/var/log/nginx
      - $PWD/nginx/slave.html:/usr/share/nginx/html/index.html
      - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/config/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - $PWD/config/keepalived/keepalived-slave.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - api_master
      - api_slave
    network_mode: host
    ports:
      - 8082:80
    cap_add: 
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW

  proxy:
    build:
      context: $PWD/haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - $PWD/config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - nginx_master
      - nginx_slave
    network_mode: host
    ports:
      - 8080:80

