// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/kokutas/vs/area/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeSaveHandler(m, endpoints, options["Save"])
	makeGetHandler(m, endpoints, options["Get"])
	makeGetByIdHandler(m, endpoints, options["GetById"])
	makeGetByCodeHandler(m, endpoints, options["GetByCode"])
	makeGetByNameHandler(m, endpoints, options["GetByName"])
	makeGetByTimeZoneHandler(m, endpoints, options["GetByTimeZone"])
	makeGetByLanguageHandler(m, endpoints, options["GetByLanguage"])
	makeGetByStateHandler(m, endpoints, options["GetByState"])
	makeGetByCreateTimeHandler(m, endpoints, options["GetByCreateTime"])
	makeGetByUpdateTimeHandler(m, endpoints, options["GetByUpdateTime"])
	makeGetByDeleteTimeHandler(m, endpoints, options["GetByDeleteTime"])
	makeUpdateCodeHandler(m, endpoints, options["UpdateCode"])
	makeUpdateNameHandler(m, endpoints, options["UpdateName"])
	makeUpdateTimeZoneHandler(m, endpoints, options["UpdateTimeZone"])
	makeUpdateLanguageHandler(m, endpoints, options["UpdateLanguage"])
	makeUpdateStateHandler(m, endpoints, options["UpdateState"])
	makeDeleteByIdHandler(m, endpoints, options["DeleteById"])
	makeDeleteByCodeHandler(m, endpoints, options["DeleteByCode"])
	makeDeleteByNameHandler(m, endpoints, options["DeleteByName"])
	makeDeleteByStateHandler(m, endpoints, options["DeleteByState"])
	return m
}
