/*
 * @Author: kokutas
 * @Email: xxx
 * @Phone: xxx
 * @Date: 2022-04-16 05:07:35
 * @LastEditors: kokutas
 * @LastEditTime: 2022-04-16 05:14:16
 * @FilePath: /area/pkg/grpc/handler_gen.go
 * @Description: TODO
 * Copyright (c) 2022 by kokutas, All Rights Reserved. 
 */
// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/kokutas/vs/area/pkg/endpoint"
 "github.com/kokutas/pb/area"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	save            grpc.Handler
	get             grpc.Handler
	getById         grpc.Handler
	getByCode       grpc.Handler
	getByName       grpc.Handler
	getByTimeZone   grpc.Handler
	getByLanguage   grpc.Handler
	getByState      grpc.Handler
	getByCreateTime grpc.Handler
	getByUpdateTime grpc.Handler
	getByDeleteTime grpc.Handler
	updateCode      grpc.Handler
	updateName      grpc.Handler
	updateTimeZone  grpc.Handler
	updateLanguage  grpc.Handler
	updateState     grpc.Handler
	deleteById      grpc.Handler
	deleteByCode    grpc.Handler
	deleteByName    grpc.Handler
	deleteByState   grpc.Handler
	area.UnimplementedAreaServiceServer
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) area.AreaServiceServer {
	return &grpcServer{
		deleteByCode:    makeDeleteByCodeHandler(endpoints, options["DeleteByCode"]),
		deleteById:      makeDeleteByIdHandler(endpoints, options["DeleteById"]),
		deleteByName:    makeDeleteByNameHandler(endpoints, options["DeleteByName"]),
		deleteByState:   makeDeleteByStateHandler(endpoints, options["DeleteByState"]),
		get:             makeGetHandler(endpoints, options["Get"]),
		getByCode:       makeGetByCodeHandler(endpoints, options["GetByCode"]),
		getByCreateTime: makeGetByCreateTimeHandler(endpoints, options["GetByCreateTime"]),
		getByDeleteTime: makeGetByDeleteTimeHandler(endpoints, options["GetByDeleteTime"]),
		getById:         makeGetByIdHandler(endpoints, options["GetById"]),
		getByLanguage:   makeGetByLanguageHandler(endpoints, options["GetByLanguage"]),
		getByName:       makeGetByNameHandler(endpoints, options["GetByName"]),
		getByState:      makeGetByStateHandler(endpoints, options["GetByState"]),
		getByTimeZone:   makeGetByTimeZoneHandler(endpoints, options["GetByTimeZone"]),
		getByUpdateTime: makeGetByUpdateTimeHandler(endpoints, options["GetByUpdateTime"]),
		save:            makeSaveHandler(endpoints, options["Save"]),
		updateCode:      makeUpdateCodeHandler(endpoints, options["UpdateCode"]),
		updateLanguage:  makeUpdateLanguageHandler(endpoints, options["UpdateLanguage"]),
		updateName:      makeUpdateNameHandler(endpoints, options["UpdateName"]),
		updateState:     makeUpdateStateHandler(endpoints, options["UpdateState"]),
		updateTimeZone:  makeUpdateTimeZoneHandler(endpoints, options["UpdateTimeZone"]),
	}
}
